title: Marina Togn
description: Junior Full-Stack Developer | HRIS & Data Analyst Background
remote_theme: "mmistakes/minimal-mistakes@3.7.0"
minimal_mistakes_skin: "dark"

author:
  name   : "Marina Togn"
  avatar : /assets/images/profilepic.png